// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pimnuaxlznsaikxhsayc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpbW51YXhsem5zYWlreGhzYXljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDE0ODAsImV4cCI6MjA2OTcxNzQ4MH0.VoaDrZqb80VU3VZ0Whe7Bzco7-Komil5tufUzmsSl50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});